import os

BROKER_URL = os.environ.get("CLOUDAMQP_URL")
CELERY_RESULT_BACKEND = os.environ.get("REDISTOGO_URL")
CELERY_IMPORTS = ('loader', )
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_EVENT_SERIALIZER = 'json'
# CELERY_EAGER_PROPAGATES_EXCEPTIONS = True
BROKER_POOL_LIMIT = 3
CELERY_REDIS_MAX_CONNECTIONS = 10
